{ 
  'Atlanta': {'Full Name': 'Atlanta Hawks', 
              'Abbreviation': 'ATL'},
  'Boston': {'Full Name': 'Boston Celtics', 
             'Abbreviation': 'BOS'},   
  'Brooklyn': {'Full Name': 'Brooklyn Nets',
               'Abbreviation': 'BRK'},
  'Chicago': {'Full Name': 'Chicago Bulls',
              'Abbreviation': 'CHI'},
  'Charlotte': {'Full Name': 'Charlotte Hornets',
                'Abbreviation': 'CHO'},
  'Cleveland': {'Full Name': 'Cleveland Cavaliers',
                'Abbreviation': 'CLE'},  
  'Dallas': {'Full Name': 'Dallas Mavericks',
             'Abbreviation': 'DAL'},  
  'Denver': {'Full Name': 'Denver Nuggets',
             'Abbreviation': 'DEN'},  
  'Detroit': {'Full Name': 'Detroit Pistons',
              'Abbreviation': 'DET'},  
  'Golden State':  {'Full Name': 'Golden State Warriors',
                    'Abbreviation': 'GSW'},  
  'Houston': {'Full Name': 'Houston Rockets',
              'Abbreviation': 'HOU'},
  'Indiana': {'Full Name': 'Indiana Pacers',
              'Abbreviation': 'IND'},
  'LA Clippers': {'Full Name': 'Los Angeles Clippers',
                  'Abbreviation': 'LAC'},
  'LA Lakers': {'Full Name': 'Los Angeles Lakers',
                'Abbreviation': 'LAL'},
  'Miami': {'Full Name': 'Miami Heat',
            'Abbreviation': 'MIA'},
  'Milwaukee': {'Full Name': 'Milwaukee Bucks',
                'Abbreviation': 'MIL'},
  'Minnesota': {'Full Name': 'Minnesota Timberwolves',
                'Abbreviation': 'MIN'},
  'Memphis': {'Full Name': 'Memphis Grizzlies',
              'Abbreviation': 'MEM'},
  'New Orleans': {'Full Name': 'New Orleans Pelicans',
                  'Abbreviation': 'NOP'},
  'New York': {'Full Name': 'New York Knicks',
               'Abbreviation': 'NYK'},
  'Oklahoma City': {'Full Name': 'Oklahoma City Thunder',
                    'Abbreviation': 'OKC'},
  'Orlando': {'Full Name': 'Orlando Magic',
              'Abbreviation': 'ORL'},
  'Philadelphia': {'Full Name': 'Philadelphia 76ers',
                   'Abbreviation': 'PHI'},
  'Phoenix': {'Full Name': 'Phoenix Suns',
              'Abbreviation': 'PHO'},
  'Portland': {'Full Name': 'Portland Trail Blazers',
               'Abbreviation': 'POR'},
  'Sacramento': {'Full Name': 'Sacramento Kings',
                 'Abbreviation': 'SAC'},
  'San Antonio': {'Full Name': 'San Antonio Spurs', 
                  'Abbreviation': 'SAS'},
  'Toronto': {'Full Name': 'Toronto Raptors',
              'Abbreviation': 'TOR'},
  'Utah': {'Full Name': 'Utah Jazz',
           'Abbreviation': 'UTA'},
  'Washington': {'Full Name': 'Washington Wizards',
                 'Abbreviation': 'WAS'}
 }